import styles from "../styles/Calendar.module.css";
export const daysOfWeek = [
  "Понеделник - 29",
  "Вторник - 30",
  "Сряда - 31",
  "Четвъртък - 01",
  "Петък - 02",
  "Събота - 03",
  "Неделя - 04",
];

export const timeSlots = [/*"01:00", "02:00", "03:00", "04:00", "05:00", "06:00", "07:00", "08:00","09:00","10:00",*/"11:00", "12:00", "13:00","14:00", "15:00", "16:00", "17:00", "18:00", "19:00", "20:00","21:00", "22:00", "23:00", "24:00"];

export const getLevelColor = (level) => {
  const levelColors = {
    "A1-1": styles.levelLightGreen,
    "A1-2": styles.levelGreen,
    "A2-1": styles.levelDarkGreen,
    "A2-2": styles.levelLightOrange,
    "B1-1": styles.levelOrange,
    "B1-2": styles.levelDarkOrange,
    "B2": styles.levelRed,
  };

  return levelColors[level];
};

export const events = [
  {
    day: "Понеделник - 29",
    startTime: "11:00",
    endTime: "12:00",
    levels: ["A1-1", "A1-2"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Вторник - 30",
    startTime: "11:00",
    endTime: "12:00",
    levels: ["A1-1", "A1-2"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Сряда - 31",
    startTime: "11:00",
    endTime: "12:00",
    levels: ["A2-2", "B1-1"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Понеделник - 29",
    startTime: "16:00",
    endTime: "17:00",
    levels: ["A2-1"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Събота - 03",
    startTime: "16:00",
    endTime: "17:00",
    levels: ["A2-1", "A2-2"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Неделя - 04",
    startTime: "16:00",
    endTime: "17:00",
    levels: ["A2-2", "B1-1"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Четвъртък - 01",
    startTime: "11:00",
    endTime: "12:00",
    levels: ["A2-2", "B1-1"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },

  {
    day: "Понеделник - 29",
    startTime: "12:30",
    endTime: "13:30",
    levels: ["A2-2", "B1-1"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Вторник - 30",
    startTime: "12:30",
    endTime: "13:30",
    levels: ["B1-2", "B2"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Сряда - 31",
    startTime: "12:30",
    endTime: "13:30",
    levels: ["A1-1", "A1-2"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Четвъртък - 01",
    startTime: "14:30",
    endTime: "15:30",
    levels: ["A1-1", "A1-2"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Неделя - 04",
    startTime: "12:30",
    endTime: "13:30",
    levels: ["B1-1", "B2"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Събота - 03",
    startTime: "15:00",
    endTime: "16:00",
    levels: ["B1-1", "B1-2"],
    title: "Английски език",
    teacher: "Лора",
    imageUrl: "/Lora.png",
    isExtra: false
  },
  {
    day: "Понеделник - 29",
    startTime: "22:00",
    endTime: "23:00",
    levels: ["B1-1", "B2"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
    isExtra: true
  },
  {
    day: "Събота - 03",
    startTime: "11:00",
    endTime: "12:00",
    levels: ["A1-2", "A2-1"],
    title: "Английски език",
    teacher: "Лилия",
    imageUrl: "/Lilia.png",
  },
  {
    day: "Неделя - 04",
    startTime: "11:00",
    endTime: "12:00",
    levels: ["A1-1", "A1-2"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Четвъртък - 01",
    startTime: "23:00",
    endTime: "24:00",
    levels: ["A2-2", "B1-1", "B1-2", "B2"],
    title: "Английски език",
    teacher: "Лара",
    imageUrl: "/Lara.png",
  },
  {
    day: "Събота - 03",
    startTime: "19:30",
    endTime: "20:30",
    levels: ["A1-1", "A2-1"],
    title: "Английски език",
    teacher: "Лора",
    imageUrl: "/Lora.png",
  },
  {
    day: "Сряда - 31",
    startTime: "21:00",
    endTime: "22:00",
    levels: ["B1-1", "B2"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
    isExtra: true
  },
  {
    day: "Събота - 03",
    startTime: "20:00",
    endTime: "21:00",
    levels: ["A1-2", "A2-1"],
    title: "Английски език",
    teacher: "Лилия",
    imageUrl: "/Lilia.png",
  },
  {
    day: "Четвъртък - 01",
    startTime: "17:00",
    endTime: "18:00",
    levels: ["A1-1", "A1-2"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Четвъртък - 01",
    startTime: "13:30",
    endTime: "14:30",
    levels: ["A2-2", "B1-1", "B1-2", "B2"],
    title: "Английски език",
    teacher: "Лара",
    imageUrl: "/Lara.png",
  },
  {
    day: "Събота - 03",
    startTime: "13:30",
    endTime: "14:30",
    levels: ["A1-1", "A2-1"],
    title: "Английски език",
    teacher: "Лора",
    imageUrl: "/Lora.png",
  },
  {
    day: "Понеделник - 29",
    startTime: "20:00",
    endTime: "21:00",
    levels: ["A1-1", "A1-2"],
    title: "Английски език",
    teacher: "Лора",
    imageUrl: "/Lora.png",
  },
  {
    day: "Вторник - 30",
    startTime: "19:00",
    endTime: "20:00",
    levels: ["A1-1", "A1-2"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Сряда - 31",
    startTime: "20:00",
    endTime: "21:00",
    levels: ["A2-2", "B1-1"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
  {
    day: "Понеделник - 29",
    startTime: "18:00",
    endTime: "19:00",
    levels: ["A2-1"],
    title: "Английски език",
    teacher: "Коце",
    imageUrl: "/Koce.png",
  },
];